 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.831E-01  1.720E-12  1.417E+07  9.176E+06 -7.561E+06  0.000E+00  0.000E+00 -3.339E+07  6.549E+06  0.000E+00  2.941E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.831E-01  1.720E-12  1.417E+07  9.176E+06 -7.561E+06  0.000E+00  0.000E+00 -3.339E+07  6.549E+06  0.000E+00  2.941E+07  0.000E+00
