 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -4.386E-03 -6.821E-13  1.555E+07  1.804E+07  0.000E+00  0.000E+00  0.000E+00 -3.917E+07  0.000E+00  0.000E+00  4.166E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -4.386E-03 -6.821E-13  1.555E+07  1.804E+07  0.000E+00  0.000E+00  0.000E+00 -3.917E+07  0.000E+00  0.000E+00  4.166E+07  0.000E+00
