 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   2.874E-01  0.000E+00  4.176E+06  2.623E+07 -5.740E+06  0.000E+00  0.000E+00 -1.933E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   2.874E-01  0.000E+00  4.176E+06  2.623E+07 -5.740E+06  0.000E+00  0.000E+00 -1.933E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
