python validate_nandrad.py -c="600" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
python validate_nandrad.py -c="600FF" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="610" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="620" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="630" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="640" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="650" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="650FF" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="900" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="900FF" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="910" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="920" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="930" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python validate_nandrad.py -c="940" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2"
rem python validate_nandrad.py -c="950" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
rem python vrem alidate_nandrad.py -c="950FF" -v="v1" -w="ZONE SUBSURFACE 1,ZONE SUBSURFACE 2 "
pause