 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.992E-01 -7.407E-13  2.258E+07  2.660E+06 -6.874E+06  0.000E+00  0.000E+00 -1.960E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.992E-01 -7.407E-13  2.258E+07  2.660E+06 -6.874E+06  0.000E+00  0.000E+00 -1.960E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
