 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -4.485E-03  0.000E+00  1.828E+07  1.776E+07  0.000E+00  0.000E+00  0.000E+00 -3.070E+07  0.000E+00  0.000E+00  3.018E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -4.485E-03  0.000E+00  1.828E+07  1.776E+07  0.000E+00  0.000E+00  0.000E+00 -3.070E+07  0.000E+00  0.000E+00  3.018E+07  0.000E+00
