 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.605E-01 -7.105E-14  8.873E+06  2.370E+07 -7.942E+06  0.000E+00  0.000E+00 -2.436E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.605E-01 -7.105E-14  8.873E+06  2.370E+07 -7.942E+06  0.000E+00  0.000E+00 -2.436E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
