 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -1.465E-03  0.000E+00  1.781E+07  2.732E+07  0.000E+00  0.000E+00  0.000E+00 -3.214E+07  0.000E+00  0.000E+00  4.165E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -1.465E-03  0.000E+00  1.781E+07  2.732E+07  0.000E+00  0.000E+00  0.000E+00 -3.214E+07  0.000E+00  0.000E+00  4.165E+07  0.000E+00
