 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.946E-01 -1.720E-12  1.715E+07  6.018E+06 -7.366E+06  0.000E+00  0.000E+00 -3.115E+07  6.549E+06  0.000E+00  2.083E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.946E-01 -1.720E-12  1.715E+07  6.018E+06 -7.366E+06  0.000E+00  0.000E+00 -3.115E+07  6.549E+06  0.000E+00  2.083E+07  0.000E+00
