 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   2.365E-01  3.411E-13  3.244E+07  1.264E+05 -6.196E+06  0.000E+00  0.000E+00 -2.612E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00   2.365E-01  3.411E-13  3.244E+07  1.264E+05 -6.196E+06  0.000E+00  0.000E+00 -2.612E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
