 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -6.114E-03 -1.421E-14  1.887E+07  1.266E+04  0.000E+00  0.000E+00  0.000E+00 -1.886E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -6.114E-03 -1.421E-14  1.887E+07  1.266E+04  0.000E+00  0.000E+00  0.000E+00 -1.886E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
