 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -1.405E-03  0.000E+00  1.872E+07  1.796E+07  0.000E+00  0.000E+00  0.000E+00 -3.122E+07  0.000E+00  0.000E+00  3.046E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -1.405E-03  0.000E+00  1.872E+07  1.796E+07  0.000E+00  0.000E+00  0.000E+00 -3.122E+07  0.000E+00  0.000E+00  3.046E+07  0.000E+00
