 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.484E-01 -1.897E-12  8.169E+06  4.380E+06 -7.816E+06  0.000E+00  0.000E+00 -3.540E+07  6.549E+06  0.000E+00  3.288E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.484E-01 -1.897E-12  8.169E+06  4.380E+06 -7.816E+06  0.000E+00  0.000E+00 -3.540E+07  6.549E+06  0.000E+00  3.288E+07  0.000E+00
