 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.950E-01  0.000E+00  3.928E+07  3.228E+06 -1.148E+07  0.000E+00  0.000E+00 -2.457E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.950E-01  0.000E+00  3.928E+07  3.228E+06 -1.148E+07  0.000E+00  0.000E+00 -2.457E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
