 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -2.182E-03  0.000E+00  2.089E+07  3.062E+06  0.000E+00  0.000E+00  0.000E+00 -1.783E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -2.182E-03  0.000E+00  2.089E+07  3.062E+06  0.000E+00  0.000E+00  0.000E+00 -1.783E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
