 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.171E-03  0.000E+00  2.179E+07  3.002E+06  0.000E+00  0.000E+00  0.000E+00 -2.533E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.171E-03  0.000E+00  2.179E+07  3.002E+06  0.000E+00  0.000E+00  0.000E+00 -2.533E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
