 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.587E-01 -7.603E-13  1.009E+07  4.663E+06 -7.675E+06  0.000E+00  0.000E+00 -3.475E+07  6.549E+06  0.000E+00  3.046E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.587E-01 -7.603E-13  1.009E+07  4.663E+06 -7.675E+06  0.000E+00  0.000E+00 -3.475E+07  6.549E+06  0.000E+00  3.046E+07  0.000E+00
