 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.770E-01 -2.046E-12  1.774E+07  1.562E+07 -7.529E+06  0.000E+00  0.000E+00 -3.401E+07  6.549E+06  0.000E+00  3.288E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.770E-01 -2.046E-12  1.774E+07  1.562E+07 -7.529E+06  0.000E+00  0.000E+00 -3.401E+07  6.549E+06  0.000E+00  3.288E+07  0.000E+00
