 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -5.562E-04  0.000E+00  1.999E+07  1.198E+07  0.000E+00  0.000E+00  0.000E+00 -2.938E+07  0.000E+00  0.000E+00  2.137E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -5.562E-04  0.000E+00  1.999E+07  1.198E+07  0.000E+00  0.000E+00  0.000E+00 -2.938E+07  0.000E+00  0.000E+00  2.137E+07  0.000E+00
