 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.869E-01  1.421E-12  1.997E+07  9.262E+06 -7.254E+06  0.000E+00  0.000E+00 -3.083E+07  6.549E+06  0.000E+00  2.083E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.869E-01  1.421E-12  1.997E+07  9.262E+06 -7.254E+06  0.000E+00  0.000E+00 -3.083E+07  6.549E+06  0.000E+00  2.083E+07  0.000E+00
