 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.847E-01 -7.958E-13  1.833E+07  1.384E+07 -7.460E+06  0.000E+00  0.000E+00 -3.300E+07  6.549E+06  0.000E+00  2.941E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.847E-01 -7.958E-13  1.833E+07  1.384E+07 -7.460E+06  0.000E+00  0.000E+00 -3.300E+07  6.549E+06  0.000E+00  2.941E+07  0.000E+00
