 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   2.009E-01  1.791E-12  2.075E+07  1.015E+06 -6.884E+06  0.000E+00  0.000E+00 -1.940E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00   2.009E-01  1.791E-12  2.075E+07  1.015E+06 -6.884E+06  0.000E+00  0.000E+00 -1.940E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
