 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.824E-01 -3.070E-12  1.741E+07  2.162E+07 -7.594E+06  0.000E+00  0.000E+00 -3.533E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.824E-01 -3.070E-12  1.741E+07  2.162E+07 -7.594E+06  0.000E+00  0.000E+00 -3.533E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
