 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.475E-01  1.421E-14  7.015E+06  8.257E+06 -8.092E+06  0.000E+00  0.000E+00 -3.779E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.475E-01  1.421E-14  7.015E+06  8.257E+06 -8.092E+06  0.000E+00  0.000E+00 -3.779E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
