 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00  -6.298E-03  2.061E-13  2.601E+07  4.566E+04  0.000E+00  0.000E+00  0.000E+00 -2.596E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00  -6.298E-03  2.061E-13  2.601E+07  4.566E+04  0.000E+00  0.000E+00  0.000E+00 -2.596E+07  0.000E+00  0.000E+00  0.000E+00  0.000E+00
