 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   9.124E-04  0.000E+00  1.815E+07  2.073E+07  0.000E+00  0.000E+00  0.000E+00 -3.118E+07  0.000E+00  0.000E+00  3.375E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   9.124E-04  0.000E+00  1.815E+07  2.073E+07  0.000E+00  0.000E+00  0.000E+00 -3.118E+07  0.000E+00  0.000E+00  3.375E+07  0.000E+00
