 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.777E-01  1.137E-13  1.576E+07  2.264E+07 -7.704E+06  0.000E+00  0.000E+00 -3.254E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.777E-01  1.137E-13  1.576E+07  2.264E+07 -7.704E+06  0.000E+00  0.000E+00 -3.254E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
