 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.822E-01  1.329E-12  1.825E+07  1.393E+07 -7.481E+06  0.000E+00  0.000E+00 -3.384E+07  6.549E+06  0.000E+00  3.046E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.822E-01  1.329E-12  1.825E+07  1.393E+07 -7.481E+06  0.000E+00  0.000E+00 -3.384E+07  6.549E+06  0.000E+00  3.046E+07  0.000E+00
