 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   2.228E-01 -2.501E-12  2.787E+07  3.940E+05 -6.411E+06  0.000E+00  0.000E+00 -2.761E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
 Energy balance for sum of all zone
   0       0.00   2.228E-01 -2.501E-12  2.787E+07  3.940E+05 -6.411E+06  0.000E+00  0.000E+00 -2.761E+07  6.549E+06  0.000E+00  0.000E+00  0.000E+00
