 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   3.491E-02 -4.423E+03  0.000E+00  0.000E+00 -4.612E+06 -1.709E+07  0.000E+00 -2.543E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   3.491E-02 -4.423E+03  0.000E+00  0.000E+00 -4.612E+06 -1.709E+07  0.000E+00 -2.543E+07  6.549E+06  0.000E+00  4.058E+07  0.000E+00
