 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    +QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.853E-01 -5.969E-13  2.369E+07  2.315E+07 -7.464E+06  0.000E+00  0.000E+00 -4.787E+07  6.549E+06  0.000E+00  4.824E+07  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.853E-01 -5.969E-13  2.369E+07  2.315E+07 -7.464E+06  0.000E+00  0.000E+00 -4.787E+07  6.549E+06  0.000E+00  4.824E+07  0.000E+00
